apiVersion: v1
kind: Service
metadata:
  name: acme-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
---
apiVersion: runtime.wasmcloud.dev/v1alpha1
kind: WorkloadDeployment
metadata:
  name: acme-app
spec:
  replicas: 1
  template:
    spec:
      hostSelector:
        hostgroup: default
      kubernetes:
        service:
          name: acme-app
      components:
        - name: acme-app
          image: azurecr.io/acme-app/acme-app:0.1
          # imagePullSecret:
          #   name: registry-secret
      hostInterfaces:
        - namespace: wasi
          package: http
          interfaces:
            - incoming-handler
          config:
            host: localhost
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: acme-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - path: /acme-app(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: acme-app
            port:
              number: 80
